[phases.setup]
nixPkgs = ["...", "php82Extensions.gd"] # Tambahkan ekstensi jika perlu

[phases.build]
cmds = ["composer install --no-dev", "npm install && npm run build"]

[phases.deploy]
cmds = ["php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT"]